### ISSUE TITLE
ConcurrentModificationException in JavaMessageSerializer.serializeMessage

### ISSUE THREAD

**Issue by Fiurgeist** [electronicarts/orbit#142]
I get the exception below when sending a lot of messages in a for loop.
I don't have a repo I can easily share but it was something like sending ~20000 msg in ~4 seconds.

Basically the problem is that the serialization code of the standard collections (like HashMap, ArrayList, etc.) is not thread safe and must be handled in the application (either cloning or synchronising)

```
15:18:46.772 [ForkJoinPool-1-worker-228] ERROR c.e.o.a.runtime.SerializationHandler - Error serializing message
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[na:1.8.0_65]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453) ~[na:1.8.0_65]
	at java.util.HashSet.writeObject(HashSet.java:286) ~[na:1.8.0_65]
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[na:1.8.0_65]
	at com.ea.orbit.actors.runtime.JavaMessageSerializer.serializeMessage(JavaMessageSerializer.java:62) ~[orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.runtime.SerializationHandler.write(SerializationHandler.java:69) ~[orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.net.DefaultHandlerContext.write(DefaultHandlerContext.java:158) [orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.runtime.MessageLoopback.write(MessageLoopback.java:85) [orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.net.DefaultHandlerContext.write(DefaultHandlerContext.java:158) [orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.runtime.Messaging.writeMessage(Messaging.java:398) [orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.runtime.Messaging.writeInvocation(Messaging.java:360) [orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.runtime.Messaging.write(Messaging.java:320) [orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.net.DefaultHandlerContext.write(DefaultHandlerContext.java:158) [orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.runtime.Hosting.async$writeInvocation(Hosting.java:724) [orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.concurrent.TaskContext.lambda$wrap$21(TaskContext.java:215) ~[orbit-commons-0.7.1.jar:na]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[na:1.8.0_65]
	at com.ea.orbit.concurrent.Task.internalComplete(Task.java:103) ~[orbit-commons-0.7.1.jar:na]
	at com.ea.orbit.concurrent.Task.lambda$from$3(Task.java:154) ~[orbit-commons-0.7.1.jar:na]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[na:1.8.0_65]
	at com.ea.orbit.concurrent.Task.internalComplete(Task.java:103) ~[orbit-commons-0.7.1.jar:na]
	at com.ea.orbit.concurrent.Task.lambda$from$3(Task.java:154) ~[orbit-commons-0.7.1.jar:na]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1595) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) ~[na:1.8.0_65]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_65]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_65]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_65]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_65]
[...]
15:18:46.776 [ForkJoinPool-1-worker-228] ERROR c.e.o.a.net.DefaultHandlerContext - Error writing: 
com.ea.orbit.exception.UncheckedException: Error serializing message
	at com.ea.orbit.actors.runtime.SerializationHandler.write(SerializationHandler.java:79) ~[orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.net.DefaultHandlerContext.write(DefaultHandlerContext.java:158) [orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.runtime.MessageLoopback.write(MessageLoopback.java:85) [orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.net.DefaultHandlerContext.write(DefaultHandlerContext.java:158) [orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.runtime.Messaging.writeMessage(Messaging.java:398) [orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.runtime.Messaging.writeInvocation(Messaging.java:360) [orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.runtime.Messaging.write(Messaging.java:320) [orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.net.DefaultHandlerContext.write(DefaultHandlerContext.java:158) [orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.runtime.Hosting.async$writeInvocation(Hosting.java:724) [orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.concurrent.TaskContext.lambda$wrap$21(TaskContext.java:215) ~[orbit-commons-0.7.1.jar:na]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[na:1.8.0_65]
	at com.ea.orbit.concurrent.Task.internalComplete(Task.java:103) ~[orbit-commons-0.7.1.jar:na]
	at com.ea.orbit.concurrent.Task.lambda$from$3(Task.java:154) ~[orbit-commons-0.7.1.jar:na]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[na:1.8.0_65]
	at com.ea.orbit.concurrent.Task.internalComplete(Task.java:103) ~[orbit-commons-0.7.1.jar:na]
	at com.ea.orbit.concurrent.Task.lambda$from$3(Task.java:154) ~[orbit-commons-0.7.1.jar:na]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1595) ~[na:1.8.0_65]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) ~[na:1.8.0_65]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_65]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_65]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_65]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_65]
Caused by: java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[na:1.8.0_65]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453) ~[na:1.8.0_65]
	at java.util.HashSet.writeObject(HashSet.java:286) ~[na:1.8.0_65]
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174) ~[na:1.8.0_65]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[na:1.8.0_65]
	at com.ea.orbit.actors.runtime.JavaMessageSerializer.serializeMessage(JavaMessageSerializer.java:62) ~[orbit-actors-stage-0.7.1.jar:na]
	at com.ea.orbit.actors.runtime.SerializationHandler.write(SerializationHandler.java:69) ~[orbit-actors-stage-0.7.1.jar:na]
	... 30 common frames omitted
```

**Comment by JoeHegarty** [comment]
Do you have an example of the message you are sending? Are you sending a collection and then modifying it?

My assumption based on the callstack and haven discussed it a little, is that there is a collection being sent in the message that is being modified before messaging has finished serializing the object.

It's not clear to me whether cloning the object on the main thread is desirable or not. It clearly has performance implications, but would improve safety. In other areas we make the assumption that objects are mutable, but allow application developers to tag them as immutable to improve performance. Perhaps something similar would work here.

If you could provide some more details on the case you're seeing this, we can decide how to proceed.

**Comment by Fiurgeist** [comment]
Ah ok I found it, there was a HashSet in one of the objects I send in a message, after cloning it before sending I don't get the error any more.
So I guess it's not really a bug, but it should be mentioned in the docu that collections send over msgs must be effectively immutable (either clones or local vars etc.).
We actually did it already in all other cases, but it somehow wasn't done for this one msg...

**Comment by johnou** [comment]
@Fiurgeist heads up, depending on your usage a shallow clone might not be enough, you may need to clone each item in the set and return that in a new set.

**Comment by Fiurgeist** [comment]
yes, we created a separate DTO because not all values were needed anyway

**Comment by JoeHegarty** [comment]
I'll close this for now, but we may wish to revisit this to make the framework safer around serialization.
