### ISSUE TITLE
NPE sending message

### ISSUE THREAD

**Issue by johnou** [electronicarts/orbit#47]
Issue with shutdown sequence?

2015-05-05 10:17:46,085 ERROR [ForkJoinPool-3-worker-299] (com.ea.orbit.actors.runtime.Hosting) Error locating server for X
    java.util.concurrent.CompletionException: com.ea.orbit.exception.UncheckedException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1926)
        at com.ea.orbit.actors.runtime.Hosting.selectNode(Hosting.java:331)
        at com.ea.orbit.actors.runtime.Hosting.lambda$locateAndActivateActor$31(Hosting.java:264)
        at com.ea.orbit.actors.runtime.Hosting$$Lambda$27/1732246598.get(Unknown Source)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582)
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
    Caused by: com.ea.orbit.exception.UncheckedException: java.lang.NullPointerException
        at com.ea.orbit.actors.cluster.ClusterPeer.sendMessage(ClusterPeer.java:282)
        at com.ea.orbit.actors.runtime.Messaging.sendMessage(Messaging.java:377)
        at com.ea.orbit.actors.runtime.Execution.sendMessage(Execution.java:1032)
        at com.ea.orbit.actors.runtime.Execution.invoke(Execution.java:1040)
        at com.ea.orbit.actors.runtime.ActorReference.invoke(ActorReference.java:101)
        at com.ea.orbit.actors.runtime.HostingFactory$HostingReference.canActivate(HostingFactory$HostingReference.java)
        ... 9 more
    Caused by: java.lang.NullPointerException
        at com.ea.orbit.actors.cluster.ClusterPeer.sendMessage(ClusterPeer.java:278)
        ... 14 more

**Comment by DanielSperry** [comment]
Hi @johnou!

Was this during shut-down?
How are you shutting-down? stage.stop()?

Was this in the same node that was being shutdown? Or in another?

**Comment by johnou** [comment]
Hi @DanielSperry yes I believe this was during shutdown.

```
    @PreDestroy
    public void shutdown() {
        stage.stop().join();
    }
```

**Comment by DanielSperry** [comment]
Hi @johnou, could you try to replicate it with the current master version?

**Comment by johnou** [comment]
Hi @DanielSperry, just updated to 0.2.4 I will reopen the issue if we are still able to replicate the problem with shutdown.

**Comment by DanielSperry** [comment]
thanks @johnou !
