### ISSUE TITLE
Frozen class (cannot edit) when invoking actor from timer

### ISSUE THREAD

**Issue by johnou** [electronicarts/orbit#90]
2015-07-28 17:42:22,684 WARN  [ForkJoinPool-1-worker-22] (com.ea.orbit.actors.runtime.Execution) Error calling timer
com.ea.orbit.exception.UncheckedException: java.lang.RuntimeException: SpaceActorFactory$SpaceActorReference: frozen class (cannot edit)
	at com.ea.orbit.actors.runtime.ActorFactoryGenerator.getFactoryFor(ActorFactoryGenerator.java:111)
	at com.ea.orbit.actors.runtime.ReferenceFactory.getFactory(ReferenceFactory.java:84)
	at com.ea.orbit.actors.runtime.ReferenceFactory.getReference(ReferenceFactory.java:50)
	at com.ea.orbit.actors.runtime.ReferenceFactory.ref(ReferenceFactory.java:98)
	at com.ea.orbit.actors.Actor.getReference(Actor.java:74)
	at SpaceActor.objectReapingTask(SpaceActor.java:103)
	at SpaceActor$$Lambda$50/1533338994.call(Unknown Source)
	at com.ea.orbit.actors.runtime.Execution$1.lambda$run$20(Execution.java:652)
	at com.ea.orbit.actors.runtime.Execution$1$$Lambda$63/1095331087.get(Unknown Source)
	at com.ea.orbit.actors.runtime.ExecutionSerializer$Runner.run(ExecutionSerializer.java:79)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.RuntimeException: SpaceActorFactory$SpaceActorReference: frozen class (cannot edit)
	at com.ea.orbit.actors.core.shaded.javassist.ClassPool.checkNotFrozen(ClassPool.java:615)
	at com.ea.orbit.actors.core.shaded.javassist.ClassPool.makeClass(ClassPool.java:809)
	at com.ea.orbit.actors.core.shaded.javassist.ClassPool.makeClass(ClassPool.java:786)
	at com.ea.orbit.actors.runtime.ActorFactoryGenerator.makeReferenceClass(ActorFactoryGenerator.java:135)
	at com.ea.orbit.actors.runtime.ActorFactoryGenerator.getFactoryFor(ActorFactoryGenerator.java:99)
	... 14 more

**Comment by johnou** [comment]
Not a bug in the end, I was calling the actor class, not the interface when invoking getReference @DanielSperry has added in a check to make this obvious, I suspect this particular exception is thrown because we run the maven instrumentation mojo.

**Comment by DanielSperry** [comment]
As suggested by @johnou, I've added better error reporting for this condition.
I'll be pushing this change soon.

@johnou, the build time instrumentation deals with async, and doesn't touch classloaders or actor references. I think the problem is really bad error reporting an invalid argument.
